image: python:3.6

services:
  - name: rigetti/qvm
    alias: qvm
    command: ["-S"]
  - name: rigetti/quilc
    alias: quilc
    command: ["-R"]

test:
  tags:
    - github
  before_script:
    - apt-get update -y && apt-get install -y libblas-dev liblapack-dev
    - pip install -r requirements.txt && pip install -e .
  script:
    - export QVM_URL='http://qvm:5000'
    - export QUILC_URL='tcp://quilc:5555'
    - MPLBACKEND=Agg pytest
